update

diff --git a/.github/workflows/sync-proto-and-build.yml b/.github/workflows/sync-proto-and-build.yml
--- a/.github/workflows/sync-proto-and-build.yml
+++ b/.github/workflows/sync-proto-and-build.yml
@@ -38,3 +38,16 @@ jobs:
 
     - name: Build with Maven
       run: mvn clean install
+
+    - name: Commit and Push Changes
+      env:
+        SYNC_BRANCH_NAME: config/auto-sync-proto
+        GH_TOKEN: ${{ secrets.TARGET_REPO_ACCESS_TOKEN }}
+      run: |
+        git config --global user.name "GitHub Actions"
+        git config --global user.email "actions@github.com"
+        git checkout -b ${SYNC_BRANCH_NAME}
+        git add .
+        git commit -m "Sync Proto files from github-actions-test" || true # Don't fail if nothing to commit
+        git push --set-upstream origin HEAD:${SYNC_BRANCH_NAME}
+        gh pr create --title "Sync .proto files" --body "This Pull Request updates the .proto files from github-actions-test" --repo kylinVD0623/sync-proto-java --base main --head ${SYNC_BRANCH_NAME} || true # Don't fail if nothing to commit
